#!/usr/bin/bash
rm -rf "dist"

tsc || { echo "> Typescript compilation failed"; exit 1; }
echo "> Typescript compilation done"

echo "> Building frontend"
cd src/frontend
npm run build || { echo "> Frontend build failed"; exit 1; }
echo -e "\033[37m>\033[32m Build done"