#!/usr/bin/bash
echo "> Setting up app"



# Python
rm -rf ".venv" "data"

echo "> Setting up venv at .venv";
python3 -m venv .venv || { echo "> Venv setup failed"; exit 1; }

echo "> Installing requirements.txt using pip at .venv/bin/python"
".venv/bin/python" -m pip install -r "requirements.txt" || { echo "> Requirements installation failed"; exit 1; }

mkdir data  

# Node
npm install
npm run build

echo "Setup done"